import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const USER_EMAIL = "demo@clientflow.local";

// LED Light Installation for Commercial/Industrial INTERIORS ONLY
// 100 templates: 30 x 1-line, 40 x 2-line, 30 x 3-line
const TEMPLATES_1LINE = [
    "Installation LED parfaite dans nos bureaux, éclairage optimal.",
    "Excellent travail d'éclairage dans notre entrepôt, très lumineux.",
    "Équipe professionnelle et installation LED impeccable, merci !",
    "Rénovation éclairage magasin réussie, clients satisfaits.",
    "Je recommande {business_name} pour l'éclairage professionnel !",
    "Pose de dalles LED très rapide et propre, parfait.",
    "Éclairage industriel parfaitement installé, très satisfait.",
    "Travail soigné et économies d'énergie immédiates, super.",
    "Installation réglettes LED entrepôt impeccable, bravo.",
    "Lumière parfaite dans notre showroom maintenant.",
    "Excellent rapport qualité-prix pour l'éclairage bureau.",
    "LED installées dans notre usine, visibilité parfaite.",
    "Remplacement néons par LED très efficace, merci.",
    "Éclairage commercial moderne et économique, satisfait.",
    "Pose de spots LED très professionnelle, recommandé.",
    "Installation rapide malgré la surface importante.",
    "Qualité d'éclairage exceptionnelle dans nos locaux.",
    "Travaux réalisés hors horaires, aucune perturbation.",
    "Équipe compétente et installation soignée, parfait.",
    "LED haute puissance pour notre atelier, excellent.",
    "Éclairage uniforme dans tout l'open space maintenant.",
    "Installation conforme aux normes, très professionnel.",
    "Pose de luminaires suspendus LED magnifique.",
    "Rénovation éclairage restaurant réussie, ambiance top.",
    "Je recommande {business_name} sans hésitation !",
    "Travail propre et résultat lumineux, très content.",
    "Éclairage adapté à notre activité, parfait.",
    "Installation discrète et efficace, merci beaucoup.",
    "LED de qualité et pose impeccable, satisfait.",
    "Ambiance lumineuse parfaite pour notre boutique.",
];

const TEMPLATES_2LINE = [
    "Installation complète d'éclairage LED dans nos bureaux sur deux étages. Travail impeccable et consommation divisée par trois, très satisfait du résultat.",
    "Rénovation de l'éclairage de notre entrepôt de 2000m² avec dalles LED haute performance. Luminosité parfaite et conformité aux normes de travail assurée.",
    "J'ai fait appel à {business_name} pour équiper notre showroom automobile en LED. Le rendu des couleurs est parfait pour mettre en valeur les véhicules.",
    "Remplacement de tous les tubes fluorescents de notre usine par des réglettes LED. Économies d'énergie immédiates et maintenance réduite, excellent investissement.",
    "Installation d'un éclairage LED modulable dans notre salle de conférence. Ambiance adaptable selon les besoins, de la présentation à la visioconférence.",
    "Pose de dalles LED encastrées dans notre open space de 50 postes. Éclairage uniforme et confortable pour le travail sur écran, équipe très satisfaite.",
    "Rénovation lumineuse de notre restaurant avec LED d'ambiance et spots directionnels. L'atmosphère est transformée et les clients adorent.",
    "Installation d'éclairage industriel LED dans notre atelier mécanique. Visibilité parfaite sur les postes de travail, sécurité grandement améliorée.",
    "Équipement complet de notre magasin avec rails de spots LED orientables. Mise en valeur optimale des produits et ambiance commerciale réussie.",
    "Pose de luminaires LED suspendus design dans notre hall d'accueil. Première impression clients excellente maintenant, travail remarquable.",
    "Je recommande {business_name} pour leur expertise en éclairage commercial. Étude lumineuse préalable et installation parfaitement exécutée.",
    "Installation de bandeaux LED indirects dans notre cabinet médical. Ambiance apaisante pour les patients et éclairage technique pour les soins.",
    "Rénovation éclairage de notre supermarché rayon par rayon. Chaque zone a maintenant l'éclairage adapté aux produits, ventes en hausse.",
    "Pose d'éclairage LED étanche dans notre cuisine professionnelle. Conformité sanitaire assurée et luminosité optimale pour le travail.",
    "Installation de dalles LED UGR bas dans notre centre d'appels. Confort visuel maximal pour les opérateurs travaillant sur écran toute la journée.",
    "Équipement LED de notre salle de sport avec éclairage puissant et homogène. Parfait pour les différentes activités proposées dans notre club.",
    "Remplacement éclairage halogène par LED dans notre galerie d'art. Rendu des couleurs parfait et protection des œuvres contre la chaleur.",
    "Installation de spots encastrés LED dans notre hôtel pour toutes les chambres. Économies substantielles et confort client amélioré.",
    "Pose d'éclairage linéaire LED dans notre pharmacie avec mise en valeur produits. L'officine est maintenant moderne et accueillante.",
    "Rénovation lumineuse de notre agence bancaire avec LED blanc neutre professionnel. Image de marque valorisée et ambiance de confiance créée.",
    "Installation d'éclairage LED dans notre laboratoire avec normes lux respectées. Travail de précision maintenant possible dans les meilleures conditions.",
    "Équipement de notre boulangerie avec LED blanc chaud pour les viennoiseries. Produits mis en valeur et consommation électrique divisée par quatre.",
    "Pose de panneaux LED dans notre clinique vétérinaire avec zones différenciées. Salles de consultation et bloc opératoire aux normes maintenant.",
    "Installation de rubans LED pour notre bar à cocktails avec effets programmables. Ambiance unique créée et clients impressionnés.",
    "Rénovation éclairage de notre concession auto avec LED haute puissance. Les véhicules brillent et l'espace est valorisé, ventes facilitées.",
    "Je fais appel à {business_name} pour tous nos locaux maintenant. Qualité constante et service après-vente réactif sur chaque installation.",
    "Pose de luminaires LED IP65 dans notre cuisine centrale. Hygiène respectée et résistance aux lavages quotidiens parfaite.",
    "Installation d'éclairage de secours LED dans nos locaux ERP. Conformité réglementaire assurée et économies sur la maintenance.",
    "Équipement complet de notre data center avec LED basse température. Charge thermique réduite et éclairage parfait pour la maintenance.",
    "Remplacement complet de l'éclairage de notre école avec LED anti-éblouissement. Confort des élèves et enseignants grandement amélioré.",
];

const TEMPLATES_3LINE = [
    "Nous avons confié à cette entreprise l'installation LED complète de notre siège social de 3000m² et le résultat dépasse nos attentes. Chaque espace a été étudié pour un éclairage optimal adapté à son usage. Les économies d'énergie réalisées sont considérables et le confort des collaborateurs nettement amélioré.",
    "Rénovation totale de l'éclairage de notre centre commercial avec passage au tout LED sur 15000m². Le projet a été mené de nuit sans perturber l'activité des boutiques. Luminosité homogène, mise en valeur des espaces et consommation électrique divisée par quatre.",
    "J'ai fait appel à {business_name} pour équiper notre plateforme logistique en éclairage LED haute performance. De l'étude photométrique à la mise en service, tout a été parfait. Les allées sont maintenant parfaitement éclairées et la sécurité des opérateurs assurée.",
    "Installation de dalles LED dans tous les bureaux de notre immeuble tertiaire de 6 étages. Gestion centralisée de l'éclairage avec détection de présence et variation selon la lumière naturelle. Projet ambitieux parfaitement réalisé par une équipe compétente.",
    "Rénovation lumineuse complète de notre usine agroalimentaire avec LED étanches conformes aux normes HACCP. Zones de production, chambres froides et laboratoires équipés avec les bons luminaires. Audit réglementaire validé grâce à cette installation professionnelle.",
    "Nous avons fait équiper notre complexe hôtelier avec un système d'éclairage LED intelligent par cette entreprise. Chambres, couloirs, restaurant et espaces communs ont chacun leur ambiance lumineuse adaptée. Économies d'exploitation significatives et satisfaction clients au rendez-vous.",
    "Installation d'éclairage LED dans notre centre de production pharmaceutique avec normes GMP respectées. Salles blanches, laboratoires et zones de conditionnement équipés avec les luminaires adaptés à chaque classe. Validation qualification effectuée avec succès.",
    "Équipement complet de notre grande surface alimentaire avec LED secteur par secteur. Boucherie en blanc froid, boulangerie en blanc chaud, fruits et légumes avec rendu couleur optimisé. Nos produits sont maintenant valorisés et les ventes ont augmenté.",
    "Je recommande vivement {business_name} pour leur expertise en éclairage industriel LED haute puissance. Notre fonderie est maintenant parfaitement éclairée malgré les conditions difficiles. Luminaires résistants installés et maintenance facilitée.",
    "Rénovation de l'éclairage de notre musée avec LED dernière génération à spectre contrôlé. Protection des œuvres assurée et mise en valeur optimale des collections. Les visiteurs apprécient la qualité de lumière dans les salles d'exposition.",
    "Installation d'un système d'éclairage LED dynamique dans notre centre de bien-être et spa. Variations chromatiques programmables pour les différents soins et ambiances relaxantes créées. L'expérience client est transformée grâce à la lumière.",
    "Équipement de notre imprimerie avec éclairage LED haute fidélité colorimétrique installé parfaitement. Le contrôle qualité des impressions est maintenant fiable et conforme aux standards. Investissement rentabilisé par la réduction des erreurs.",
    "Nous avons fait appel à cette entreprise pour l'éclairage LED de notre studio photo professionnel. Installation technique complexe parfaitement maîtrisée avec gestion DMX intégrée. Flexibilité totale maintenant pour nos différentes productions.",
    "Rénovation lumineuse de notre établissement scolaire avec LED anti-fatigue visuelle dans les salles de classe. Tableaux parfaitement éclairés et écrans sans reflets. Le confort des élèves et enseignants est grandement amélioré.",
    "Installation d'éclairage LED dans notre parking souterrain de 500 places avec détection de présence par zone. Économies d'énergie de 80% réalisées et sécurité renforcée par la qualité de l'éclairage. Investissement amorti en deux ans.",
    "Équipement de notre atelier de peinture automobile avec cabines éclairées aux normes LED spécifiques. Température couleur parfaite pour le contrôle des teintes et uniformité d'éclairage garantie. Qualité de nos travaux reconnue depuis.",
    "Installation complète de notre clinique avec éclairage LED adapté à chaque espace médical. Salles d'examen, blocs opératoires et chambres patients équipés selon les recommandations sanitaires. Personnel et patients satisfaits.",
    "Remplacement de l'éclairage de notre bibliothèque municipale par LED confortable et économique. Espaces de lecture parfaitement éclairés et rayonnages bien mis en valeur. Ambiance studieuse préservée avec modernité apportée.",
    "Équipement de notre centre de tri postal avec LED haute puissance pour les tapis de convoyage. Lecture des étiquettes facilitée et conditions de travail améliorées pour les agents. Productivité en hausse depuis l'installation.",
    "Nous avons confié à {business_name} l'éclairage LED de notre salle de spectacle avec gradation complète. De la scène aux coulisses en passant par les loges, tout est parfaitement équipé. Les artistes et le public apprécient.",
    "Installation d'éclairage de précision LED dans notre atelier horloger. Postes de travail individuellement équipés avec lumière adaptée au travail minutieux. Confort visuel des artisans préservé malgré les heures de travail précis.",
    "Rénovation complète de notre cave vinicole avec LED sans UV ni chaleur pour préserver les vins. Mise en valeur des barriques et température stable maintenues. Nos visiteurs sont impressionnés par l'ambiance créée.",
    "Équipement de notre datacenter avec LED basse consommation et faible dégagement thermique. Allées chaudes et froides correctement éclairées pour la maintenance. PUE amélioré grâce à cette installation thermiquement optimisée.",
    "Installation d'éclairage LED dans notre centre de formation avec salles modulables. Chaque configuration a son ambiance lumineuse préenregistrée et rappelable. Formateurs et participants bénéficient de conditions optimales.",
    "Nous avons fait équiper nos cuisines centrales avec LED IP69K résistant au nettoyage haute pression. Conformité HACCP totale et luminosité parfaite sur les postes de préparation. Audit sanitaire réussi sans remarque.",
    "Installation de bandeaux LED architecturaux dans notre hall d'entreprise pour mise en valeur de l'espace. Effet visuel remarquable à l'accueil des visiteurs. L'image de marque de notre société est maintenant parfaitement reflétée.",
    "Équipement de notre magasin de vêtements avec éclairage LED CRI 95+ pour les cabines d'essayage. Les clients voient les vraies couleurs et sont rassurés dans leurs choix. Taux de retour en baisse significative.",
    "Rénovation lumineuse de notre pressing industriel avec LED haute efficacité et résistantes à la chaleur. Postes de repassage parfaitement éclairés et conditions de travail nettement améliorées. Équipe satisfaite.",
    "Installation d'éclairage LED dans notre morgue hospitalière avec normes sanitaires strictes respectées. Luminaires adaptés aux différentes zones et ambiances appropriées créées. Installation délicate parfaitement gérée.",
    "Équipement complet de notre centre aquatique avec LED IP68 pour bassins et étanches pour vestiaires. Éclairage subaquatique magnifique et sécurité assurée dans tous les espaces. Fréquentation en hausse depuis la rénovation.",
];

// 200 contexts for commercial/industrial LED interior installations
const CONTEXTS = [
    "Installation LED bureaux open space",
    "Éclairage entrepôt logistique LED",
    "Rénovation lumineuse magasin",
    "Dalles LED plafond suspendu",
    "Réglettes LED atelier industriel",
    "Spots LED commerce détail",
    "Panneaux LED salle réunion",
    "Luminaires LED restaurant",
    "Éclairage showroom automobile",
    "LED haute puissance usine",
    "Bandeaux LED indirect bureaux",
    "Éclairage LED supermarché",
    "Dalles LED hall accueil",
    "Spots orientables LED boutique",
    "Réglettes étanches LED cuisine pro",
    "Éclairage salle de sport LED",
    "LED laboratoire normes lux",
    "Éclairage pharmacie LED",
    "Luminaires LED hôtel chambres",
    "LED centre commercial allées",
    "Éclairage LED salle conférence",
    "Dalles LED clinique médicale",
    "LED usine agroalimentaire étanche",
    "Éclairage LED galerie art",
    "Spots LED bijouterie vitrine",
    "LED parking souterrain",
    "Éclairage LED école classe",
    "Luminaires LED bibliothèque",
    "LED centre appels UGR bas",
    "Éclairage LED salle serveurs",
    "Remplacement néons par LED bureaux",
    "Changement tubes fluorescents LED",
    "Rénovation éclairage usine LED",
    "Passage au LED commerce",
    "Mise à jour éclairage entrepôt",
    "Modernisation lumière magasin",
    "Remplacement halogène LED boutique",
    "Upgrade éclairage restaurant LED",
    "Conversion LED atelier",
    "Réhabilitation lumineuse locaux",
    "Dalles 600x600 LED encastrées",
    "Panneaux LED 300x1200",
    "Réglettes LED T8 remplacement",
    "Downlight LED encastré",
    "Projecteur LED industriel",
    "Applique murale LED bureau",
    "Suspension LED design",
    "Rail spots LED magasin",
    "Bandeau LED architectural",
    "Éclairage linéaire LED continu",
    "Éclairage 500 lux poste travail",
    "Normes éclairage bureaux respectées",
    "Conformité lumière atelier",
    "UGR inférieur 19 écrans",
    "Rendu couleurs CRI 90+",
    "Température 4000K neutre",
    "LED 3000K ambiance chaleureuse",
    "5000K lumière froide industriel",
    "Gradation 1-100% LED",
    "DALI éclairage intelligent",
    "Éclairage bureaux entreprise",
    "LED siège social corporate",
    "Lumière PME locaux",
    "Éclairage startup open space",
    "LED coworking espace partagé",
    "Agence bancaire éclairage",
    "Cabinet avocat luminaires",
    "Clinique vétérinaire LED",
    "Centre médical éclairage",
    "Laboratoire analyse LED",
    "Éclairage entrepôt Amazon",
    "LED plateforme logistique",
    "Centre distribution éclairage",
    "Usine production LED",
    "Atelier mécanique lumière",
    "Fonderie éclairage industriel",
    "Imprimerie LED fidélité couleur",
    "Menuiserie éclairage atelier",
    "Garage automobile LED",
    "Concession auto showroom",
    "LED grande surface alimentaire",
    "Éclairage hypermarché",
    "Supermarché rayon frais LED",
    "Boutique mode éclairage",
    "Magasin chaussures LED",
    "Bijouterie vitrine éclairage",
    "Opticien lumière essayage",
    "Parfumerie LED ambiance",
    "Boulangerie éclairage produits",
    "Boucherie LED blanc froid",
    "Restaurant gastronomique ambiance",
    "Fast food éclairage LED",
    "Bar cocktails LED ambiance",
    "Café salon de thé lumière",
    "Hôtel lobby éclairage",
    "Hôtel chambre LED",
    "Spa bien-être ambiance",
    "Salle fitness LED puissant",
    "Piscine intérieure éclairage",
    "Musée LED protection oeuvres",
    "Détection présence LED bureaux",
    "Variation lumière naturelle auto",
    "Gestion centralisée éclairage",
    "Programmation horaire LED",
    "Capteurs luminosité automatique",
    "Interrupteur crépusculaire LED",
    "Gradateur 0-10V installation",
    "Protocole DALI éclairage",
    "Système KNX lumière",
    "Domotique éclairage professionnel",
    "ROI installation LED calcul",
    "Économies énergie LED mesure",
    "Amortissement éclairage LED",
    "Consommation réduite LED",
    "Facture électricité baisse",
    "Coût maintenance réduit LED",
    "Durée vie 50000 heures",
    "Garantie 5 ans luminaires",
    "CEE prime énergie LED",
    "Subvention éclairage professionnel",
    "Certification CE luminaires",
    "Normes EN 12464-1 bureaux",
    "EN 12464-2 extérieur travail",
    "Éclairage sécurité BAES LED",
    "Blocs autonomes installation",
    "Issue secours lumineuse",
    "Éclairage anti-panique LED",
    "Plan évacuation lumineux",
    "IP20 bureaux secs",
    "IP44 zones humides",
    "IP65 cuisine professionnelle",
    "IP66 lavage haute pression",
    "IP69K agroalimentaire",
    "IK10 résistance chocs",
    "ATEX zones explosives",
    "LED chambre froide -40°C",
    "Haute température LED four",
    "Résistance vibrations industriel",
    "Éclairage alimentaire spécial",
    "LED boucherie blanc froid",
    "Boulangerie blanc chaud LED",
    "Poissonnerie éclairage bleu",
    "Fruits légumes LED naturel",
    "Vin cave LED sans UV",
    "Fromage éclairage adapté",
    "Installation planifiée weekend",
    "Travaux nocturnes magasin",
    "Phasage installation LED",
    "Zone par zone équipement",
    "Sans interruption activité",
    "Coordination chantier LED",
    "Mise en service progressive",
    "Formation personnel éclairage",
    "Documentation technique LED",
    "Rapport photométrique fourni",
    "Devis éclairage LED bureaux",
    "Étude lumineuse gratuite",
    "Audit éclairage existant",
    "Calcul luminaire nécessaire",
    "Plan implantation LED",
    "Simulation 3D éclairage",
    "Prototype zone test LED",
    "Échantillon luminaire essai",
    "Comparatif marques LED",
    "Sélection fournisseur éclairage",
    "Maintenance préventive LED",
    "Contrat entretien éclairage",
    "Remplacement luminaire SAV",
    "Dépannage éclairage urgent",
    "Pièces détachées LED",
    "Driver LED remplacement",
    "Nettoyage luminaires pro",
    "Contrôle annuel installation",
    "Mise à jour firmware LED",
    "Extension installation existante",
    "Éclairage conformité travail",
    "Normes lux poste travail",
    "Médecine travail éclairage",
    "CHSCT validation lumière",
    "Ergonomie visuelle LED",
    "Prévention fatigue oculaire",
    "Anti-éblouissement luminaires",
    "Spectre lumière naturelle",
    "Bien-être au travail LED",
    "Productivité éclairage adapté",
    "Hôpital éclairage circadien",
    "EHPAD lumière adaptée",
    "Crèche éclairage enfants",
    "École maternelle LED sécurisé",
    "Université amphithéâtre LED",
    "Centre formation éclairage",
    "Théâtre éclairage salle",
    "Cinéma LED couloirs",
    "Salle concert éclairage",
    "Studio photo LED technique",
    "Plateau TV éclairage",
    "Studio enregistrement LED",
];

async function seed() {
    console.log("💡 Seeding LED Light Install data...\n");

    const user = await prisma.user.findFirst({ where: { email: USER_EMAIL } });
    if (!user) {
        console.error(`❌ User ${USER_EMAIL} not found!`);
        return;
    }
    console.log(`✓ Found user: ${user.email}\n`);

    console.log("📝 Creating 1-line templates...");
    for (let i = 0; i < TEMPLATES_1LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `LED Install 1L-${i + 1}`,
                lines: 1,
                category: "LED_LIGHT_INSTALL",
                promptInstruction: TEMPLATES_1LINE[i],
                namePosition: TEMPLATES_1LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_1LINE.length} x 1-line templates`);

    console.log("📝 Creating 2-line templates...");
    for (let i = 0; i < TEMPLATES_2LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `LED Install 2L-${i + 1}`,
                lines: 2,
                category: "LED_LIGHT_INSTALL",
                promptInstruction: TEMPLATES_2LINE[i],
                namePosition: TEMPLATES_2LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_2LINE.length} x 2-line templates`);

    console.log("📝 Creating 3-line templates...");
    for (let i = 0; i < TEMPLATES_3LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `LED Install 3L-${i + 1}`,
                lines: 3,
                category: "LED_LIGHT_INSTALL",
                promptInstruction: TEMPLATES_3LINE[i],
                namePosition: TEMPLATES_3LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_3LINE.length} x 3-line templates`);

    console.log("\n💬 Creating contexts...");
    for (let i = 0; i < CONTEXTS.length; i++) {
        await prisma.reviewContext.create({
            data: {
                userId: user.id,
                type: "scenario",
                title: `LED Install Context ${i + 1}`,
                content: CONTEXTS[i],
                category: "LED_LIGHT_INSTALL",
                isActive: true,
            }
        });
        if ((i + 1) % 50 === 0) console.log(`   ...${i + 1} contexts`);
    }
    console.log(`   ✓ ${CONTEXTS.length} contexts`);

    const total = TEMPLATES_1LINE.length + TEMPLATES_2LINE.length + TEMPLATES_3LINE.length;
    console.log(`\n✅ Complete! ${total} templates + ${CONTEXTS.length} contexts for LED_LIGHT_INSTALL`);
}

seed()
    .catch((e) => { console.error("❌ Error:", e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
