import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const USER_EMAIL = "demo@clientflow.local";

// Templates: 30 x 1-line, 40 x 2-line, 30 x 3-line = 100 total
const TEMPLATES_1LINE = [
    "Intervention rapide et efficace, électricien très professionnel !",
    "Panne résolue en moins d'une heure, parfait travail.",
    "Électricien compétent et ponctuel, je recommande vivement.",
    "Dépannage urgent parfaitement géré, merci beaucoup !",
    "Travail propre et sécurisé, tarifs raisonnables.",
    "Installation électrique impeccable, très satisfait.",
    "Je recommande {business_name} sans hésitation !",
    "Intervention nocturne rapide, super service client.",
    "Électricien sérieux et travail de qualité, satisfait.",
    "Panne de courant résolue très rapidement, merci !",
    "Installation tableau électrique parfaite, très content.",
    "Mise aux normes rapide et efficace, excellent.",
    "Devis clair et respecté, travail impeccable.",
    "Électricien à l'écoute et très compétent.",
    "Court-circuit résolu rapidement, professionnel.",
    "Excellent rapport qualité-prix pour les travaux.",
    "Intervention en urgence très appréciée, merci.",
    "Travaux électriques parfaitement réalisés.",
    "Artisan qualifié et respectueux, je recommande.",
    "Dépannage rapide et efficace, super service !",
    "Installation prises et interrupteurs impeccable.",
    "Électricien disponible et réactif, excellent travail.",
    "Rénovation électrique magnifique, merci !",
    "Chantier propre et travail soigné, bravo.",
    "Service client au top, travail de qualité.",
    "Pose de luminaires rapide et propre, parfait.",
    "Diagnostic panne précis et réparation efficace.",
    "Électricien honnête et travail sérieux, recommandé.",
    "Installation domotique parfaite, ravi !",
    "Remplacement disjoncteur efficace et rapide.",
];

const TEMPLATES_2LINE = [
    "Intervention très rapide pour une panne électrique totale. L'électricien a diagnostiqué le problème immédiatement et l'a réparé efficacement.",
    "Rénovation complète de l'installation électrique réalisée avec soin. Travail de qualité et respect des délais, je suis très satisfait.",
    "J'ai fait appel à {business_name} pour une mise aux normes urgente. Intervention rapide et professionnelle, je recommande vivement.",
    "Remplacement du tableau électrique effectué rapidement et proprement. L'électricien a tout expliqué clairement et le prix était conforme au devis.",
    "Dépannage prise électrique qui faisait des étincelles réalisé efficacement. Le problème est résolu et l'électricien a été très professionnel.",
    "Installation d'un système domotique complet parfaitement réalisée. Je peux maintenant tout contrôler depuis mon smartphone, génial.",
    "Réparation d'un court-circuit qui faisait sauter le disjoncteur. Intervention rapide qui a évité des dégâts plus importants, merci beaucoup.",
    "Pose de spots encastrés dans tout le salon. Travail soigné et finitions impeccables, très content du résultat lumineux.",
    "Installation de prises supplémentaires dans la cuisine très rapide. L'électricien avait le matériel adapté et tout fonctionne parfaitement.",
    "Mise en sécurité de l'installation électrique ancienne parfaitement gérée. L'électricien a identifié tous les points dangereux.",
    "Installation d'un interrupteur différentiel bien réalisée. Le travail est propre et discret, exactement ce qu'il fallait.",
    "Dépannage week-end pour panne de chauffage électrique effectué rapidement. L'électricien était disponible et a résolu le problème efficacement.",
    "Pose d'un variateur de lumière moderne avec télécommande. Installation technique bien maîtrisée et résultat très pratique.",
    "Remise aux normes NF C 15-100 de mon appartement ancien. Mise aux normes effectuée proprement et dans les temps.",
    "Je recommande {business_name} pour leur sérieux et leur compétence. Installation de qualité et service client irréprochable.",
    "Intervention pour odeur de brûlé à une prise gérée en urgence. L'électricien a sécurisé et réparé le circuit immédiatement.",
    "Installation d'une borne de recharge véhicule électrique. Projet technique réalisé avec expertise et conseils pertinents.",
    "Remplacement de fils électriques vétustes très bien géré. L'électricien a su travailler sans casse dans les murs.",
    "Raccordement du nouveau four électrique effectué rapidement. Ligne dédiée créée dans les règles de l'art.",
    "Installation de détecteurs de fumée dans toute la maison. Pose rapide et explications claires sur le fonctionnement.",
    "Création d'un circuit dédié pour le climatiseur parfaitement réalisée. Plus de disjoncteur qui saute maintenant.",
    "Remplacement de tous les interrupteurs vétustes très rapide. L'électricien a tout changé en une demi-journée.",
    "Pose de réglettes LED dans le garage parfaitement réalisée. Éclairage optimal maintenant et économies d'énergie.",
    "Installation complète cuisine neuve avec tous les circuits. Travail de professionnel, aucun problème depuis.",
    "Vérification annuelle de mon installation par un pro sérieux. Conseils utiles et petites réparations préventives effectuées.",
    "Diagnostic électrique obligatoire pour vente réalisé rapidement. Rapport détaillé fourni pour l'acheteur.",
    "Pose d'un délesteur pour optimiser mon abonnement. Installation pratique qui va me faire économiser sur ma facture.",
    "Réparation volet roulant électrique bloqué très rapide. L'électricien avait les pièces et le savoir-faire.",
    "Installation d'un interphone vidéo moderne avec écran couleur. Travail technique bien maîtrisé et raccordements impeccables.",
    "Je fais appel à {business_name} depuis des années. Toujours satisfait de leur réactivité et de leur travail.",
    "Pose de prises USB intégrées aux murs très pratique. Finitions soignées et installation discrète.",
    "Installation de spots extérieurs avec détecteur de mouvement. Éclairage automatique parfaitement fonctionnel.",
    "Création d'un réseau électrique pour extension maison. Raccordement parfait au tableau existant sans coupure longue.",
    "Remplacement compteur ancien par Linky accompagné. Mise aux normes du tableau en même temps très bien gérée.",
    "Installation de convecteurs électriques nouvelle génération. Chauffage plus efficace et consommation réduite.",
    "Dépannage portail électrique en panne très bien géré. L'électricien a trouvé la panne rapidement.",
    "Pose de câbles réseau et électriques pour bureau. Travail propre avec gaines et finitions impeccables.",
    "Installation d'un gestionnaire d'énergie connecté. Suivi de ma consommation en temps réel maintenant possible.",
    "Mise aux normes salle de bain zone eau parfaitement réalisée. Sécurité totale maintenant dans cette pièce.",
    "Remplacement de l'éclairage halogène par LED économique. Même luminosité et facture électrique réduite.",
];

const TEMPLATES_3LINE = [
    "Nous avons fait appel à cet électricien pour la rénovation complète de notre installation électrique et nous sommes enchantés du résultat. Le travail est impeccable, du tableau aux prises, avec une finition parfaite. L'équipe est ponctuelle, propre et très professionnelle.",
    "Suite à une panne électrique générale un samedi soir, l'électricien est intervenu en urgence rapidement. Il a su diagnostiquer le problème et réparer efficacement malgré l'heure tardive. Service client remarquable et grand professionnalisme.",
    "J'ai fait installer un système domotique complet par {business_name} et je suis extrêmement satisfait. De l'étude technique à la mise en service et configuration, tout a été géré parfaitement. Ma maison est maintenant connectée et économe.",
    "Mise aux normes complète de notre maison des années 70 avec remplacement de toute l'installation vétuste. Le chantier a été mené proprement malgré la complexité des travaux. Nous avons maintenant une installation sûre et moderne.",
    "Installation d'une borne de recharge pour véhicule électrique avec création de la ligne dédiée depuis le tableau. L'électricien a travaillé en coordination parfaite avec mon installateur solaire. Résultat impeccable et fonctionnel.",
    "Suite à un dégât des eaux ayant endommagé l'installation électrique, l'électricien a tout réparé et sécurisé. Travail rapide et efficace qui m'a permis de retrouver l'électricité rapidement. Je recommande vivement leurs services.",
    "Nous avons confié à cet électricien la création du réseau électrique de notre extension sur deux niveaux. De la conception à la réalisation, tout a été parfait. Chaque pièce dispose des points électriques nécessaires.",
    "Installation d'un système de panneaux solaires avec onduleur et raccordement au réseau parfaitement réalisée. Travail technique complexe géré avec expertise. Je produis maintenant ma propre électricité et revends le surplus.",
    "Remplacement de tout le câblage en aluminium ancien par du cuivre aux normes actuelles. L'électricien a travaillé proprement sans dégâts sur les murs. Installation conforme et sécurisée maintenant.",
    "Je recommande vivement {business_name} pour leur professionnalisme et leur expertise en électricité. Ils ont résolu un problème de surtension que personne n'arrivait à diagnostiquer. Enfin tranquille après des mois de pannes.",
    "Installation complète d'un éclairage LED dans toute notre entreprise avec détecteurs de présence automatiques. L'électricien a su adapter les solutions aux contraintes du bâtiment. Économies d'énergie importantes réalisées.",
    "Intervention d'urgence un dimanche soir alors que toute la maison était sans électricité. L'électricien est arrivé très rapidement et a réparé le tableau défaillant. Prix correct malgré l'urgence, très reconnaissant.",
    "Création d'un local technique avec tableau secondaire pour notre atelier de menuiserie. L'électricien connaissait parfaitement les besoins en puissance des machines. Installation dimensionnée correctement.",
    "Suite à une inspection révélant une installation dangereuse, l'électricien a réalisé une mise en sécurité complète. Travaux urgents effectués rapidement pour notre sécurité. Installation aux normes maintenant.",
    "Installation de prises et éclairages dans notre jardin avec enfouissement des câbles parfaitement réalisée. L'électricien a su créer un réseau discret et fonctionnel. Terrasse éclairée magnifiquement.",
    "Pose d'un système anti-foudre et parafoudre pour protéger notre installation après plusieurs orages destructeurs. Solution technique parfaitement mise en place. Équipements protégés maintenant.",
    "Mise en sécurité complète d'un commerce avec éclairage de secours et alarme incendie conformes. Installation aux normes ERP réalisée correctement. Ouverture validée par la commission.",
    "Intervention suite à un incendie électrique heureusement limité à une prise. L'électricien a tout vérifié et remplacé les éléments dangereux. Plus jamais de risque maintenant.",
    "Installation d'un système de gestion d'énergie intelligent pour optimiser ma consommation électrique. L'électricien a configuré les plages horaires et le délestage. Facture réduite de 30 pourcent.",
    "Rénovation électrique complète d'un local professionnel transformé en restaurant. L'électricien a prévu tous les circuits cuisine et l'éclairage d'ambiance. Ouverture réussie grâce à son travail.",
    "Nous avons fait appel à {business_name} pour installer des panneaux photovoltaïques en autoconsommation avec batterie de stockage. Installation technique parfaitement réalisée. Autonomie énergétique partielle atteinte.",
    "Dépannage d'une installation triphasée industrielle que plusieurs électriciens avaient refusée. Ce professionnel a su diagnostiquer et réparer le problème complexe. Machines de nouveau opérationnelles.",
    "Installation d'un éclairage architectural pour mettre en valeur notre façade commerciale. L'électricien a su créer des effets lumineux remarquables. Notre boutique est maintenant visible de loin.",
    "Raccordement électrique de notre nouvelle maison au réseau ENEDIS parfaitement géré. De la demande aux travaux, l'électricien a tout coordonné. Emménagement sans stress électrique.",
    "Création d'un home cinéma avec installation électrique dédiée, prises, éclairage indirect et domotique. Projet ambitieux parfaitement réalisé. Expérience cinéma exceptionnelle maintenant chez nous.",
    "Mise en conformité électrique d'un camping avec bornes de branchement sécurisées pour les emplacements. Installation aux normes réalisée avant la saison. Contrôle Consuel validé du premier coup.",
    "Installation de caméras de surveillance avec alimentation POE et enregistreur centralisé. L'électricien a su combiner les compétences électriques et réseau. Surveillance 24h/24 opérationnelle.",
    "Pose d'un système de chauffage électrique par le sol dans notre extension parfaitement réalisée. Confort optimal et température homogène maintenant. L'électricien a bien dimensionné l'installation.",
    "Rénovation complète du réseau électrique d'un immeuble de bureaux avec baies de brassage. Travail technique parfaitement réalisé sans interruption d'activité. Performance réseau optimale.",
    "Installation d'un groupe électrogène de secours pour notre entreprise avec basculement automatique. Continuité d'activité assurée en cas de coupure. Investissement sécurité parfaitement réalisé.",
];

// 200 contexts
const CONTEXTS = [
    "Panne électrique générale maison",
    "Disjoncteur qui saute régulièrement",
    "Installation tableau électrique neuf",
    "Mise aux normes NF C 15-100",
    "Remplacement prises électriques vétustes",
    "Pose spots encastrés plafond",
    "Installation luminaires salon",
    "Création circuit dédié cuisine",
    "Dépannage urgent électricité",
    "Prise qui fait des étincelles",
    "Remplacement interrupteurs anciens",
    "Installation variateur lumière",
    "Pose détecteurs de fumée",
    "Installation interphone vidéo",
    "Réparation volet roulant électrique",
    "Installation borne recharge voiture",
    "Mise en sécurité installation dangereuse",
    "Diagnostic électrique obligatoire",
    "Installation domotique maison",
    "Pose prises USB murales",
    "Remplacement câbles aluminium",
    "Installation panneaux solaires",
    "Création réseau électrique extension",
    "Dépannage portail électrique",
    "Installation climatisation électrique",
    "Pose convecteurs électriques",
    "Raccordement four électrique",
    "Installation plaque induction",
    "Remplacement chauffe-eau électrique",
    "Création éclairage extérieur jardin",
    "Installation détecteur de mouvement",
    "Pose réglettes LED garage",
    "Raccordement VMC électrique",
    "Installation délesteur électrique",
    "Pose compteur divisionnaire",
    "Remplacement disjoncteur différentiel",
    "Installation parafoudre",
    "Vérification installation électrique",
    "Entretien préventif électricité",
    "Câblage réseau informatique",
    "Panne de courant dans une pièce",
    "Plus de lumière salon depuis hier",
    "Prises cuisine ne marchent plus",
    "Disjoncteur principal qui saute",
    "Odeur de brûlé prise électrique",
    "Étincelles à la prise",
    "Court-circuit répétitif",
    "Fusible qui fond régulièrement",
    "Interrupteur qui chauffe",
    "Éclair bleu au tableau",
    "Compteur qui disjoncte",
    "Tension électrique instable",
    "Ampoules qui grillent souvent",
    "Luminaire qui clignote",
    "Volet électrique bloqué",
    "Portail ne s'ouvre plus",
    "VMC qui ne tourne plus",
    "Chauffe-eau en panne",
    "Radiateur électrique défaillant",
    "Climatisation ne démarre pas",
    "Devis rénovation électrique complète",
    "Devis mise aux normes appartement",
    "Devis installation tableau neuf",
    "Devis borne de recharge VE",
    "Devis installation domotique",
    "Devis éclairage extérieur",
    "Devis panneaux photovoltaïques",
    "Devis chauffage électrique",
    "Devis alarme électrique",
    "Devis interphone résidence",
    "Électricien pour syndic copropriété",
    "Électricien agréé Consuel",
    "Contrat maintenance électrique",
    "Intervention pour bailleur",
    "Électricien disponible dimanche",
    "Urgence électricité nuit",
    "Dépannage électricien férié",
    "Électricien proche rapidement",
    "Artisan électricien qualifié",
    "Électricien pas cher fiable",
    "Tableau électrique aux normes",
    "Disjoncteur différentiel 30mA",
    "Interrupteur différentiel type A",
    "Parafoudre modulaire",
    "Délesteur électronique",
    "Contacteur jour nuit",
    "Horloge programmable tableau",
    "Télérupteur éclairage",
    "Minuterie cage escalier",
    "Prise de courant 16A",
    "Prise spécialisée 32A",
    "Interrupteur va-et-vient",
    "Interrupteur permutateur",
    "Bouton poussoir sonnette",
    "Variateur rotatif",
    "Détecteur de présence",
    "Cellule crépusculaire",
    "Programmateur hebdomadaire",
    "Thermostat électronique",
    "Gestionnaire énergie",
    "Rénovation appartement ancien",
    "Rénovation maison des années 70",
    "Mise aux normes location",
    "Sécurisation installation vétuste",
    "Remplacement fils électriques",
    "Création nouveaux circuits",
    "Augmentation puissance compteur",
    "Passage en triphasé",
    "Installation terre générale",
    "Création liaison équipotentielle",
    "Installation cuisine équipée",
    "Création îlot central électrique",
    "Raccordement électroménager",
    "Prises plan de travail",
    "Éclairage sous meuble",
    "Hotte aspirante branchement",
    "Four encastrable raccordement",
    "Plaque cuisson installation",
    "Lave-vaisselle prise dédiée",
    "Réfrigérateur américain circuit",
    "Mise aux normes salle de bain",
    "Volume de protection électrique",
    "Prise rasoir transformateur",
    "Éclairage miroir sécurisé",
    "VMC salle d'eau",
    "Sèche-serviettes électrique",
    "Radiateur soufflant mural",
    "TBTS salle de bain",
    "Interrupteur étanche IP44",
    "Classe II éclairage humidité",
    "Éclairage jardin basse tension",
    "Spots enterrés terrasse",
    "Appliques murales extérieures",
    "Projecteur détection mouvement",
    "Borne lumineuse allée",
    "Éclairage piscine sécurisé",
    "Guirlande extérieure fête",
    "Prise étanche jardin",
    "Arrosage automatique électrovanne",
    "Pompe bassin raccordement",
    "Installation bureau domotique",
    "Éclairage LED télétravail",
    "Multiprise parafoudre bureau",
    "Prises réseau RJ45",
    "Baie de brassage installation",
    "Onduleur installation serveur",
    "Installation commerce électricité",
    "Enseigne lumineuse branchement",
    "Vitrine éclairée installation",
    "Caisse enregistreuse prise",
    "Alarme commerce pose",
    "Vidéosurveillance alimentation",
    "Éclairage secours BAES",
    "Issue de secours lumineuse",
    "Bloc autonome installation",
    "Centrale incendie raccordement",
    "Local professionnel électrique",
    "Atelier artisan installation",
    "Restaurant cuisine électricité",
    "Laboratoire équipement électrique",
    "Garage automobile installation",
    "Cabinet médical normes",
    "Dentiste équipement spécial",
    "Salon coiffure installation",
    "Local industriel triphasé",
    "Entrepôt éclairage LED",
    "Panneaux photovoltaïques toiture",
    "Onduleur solaire installation",
    "Autoconsommation électrique",
    "Batterie stockage solaire",
    "Injection réseau revente",
    "Borne recharge Tesla",
    "Borne universelle voiture",
    "Wallbox installation garage",
    "Recharge copropriété borne",
    "Infrastructure recharge collective",
    "Domotique éclairage intelligent",
    "Volets roulants centralisés",
    "Chauffage connecté programmation",
    "Alarme domotique intégrée",
    "Vidéosurveillance smartphone",
    "Serrure connectée installation",
    "Assistant vocal intégration",
    "Scénarios domotiques création",
    "Capteurs température installation",
    "Détecteurs ouverture portes",
    "Intervention rapide urgence",
    "Réparation sur place",
    "Remplacement immédiat",
    "Devis gratuit express",
    "Tarif transparent affiché",
    "Garantie travaux réalisés",
    "Matériel certifié NF",
    "Électricien agréé assurances",
    "Attestation Consuel fournie",
    "Certificat conformité délivré",
];

async function seed() {
    console.log("⚡ Seeding Electrician data...\n");

    const user = await prisma.user.findFirst({ where: { email: USER_EMAIL } });
    if (!user) {
        console.error(`❌ User ${USER_EMAIL} not found!`);
        return;
    }
    console.log(`✓ Found user: ${user.email}\n`);

    console.log("📝 Creating 1-line templates...");
    for (let i = 0; i < TEMPLATES_1LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `Electrician 1L-${i + 1}`,
                lines: 1,
                category: "ELECTRICIAN",
                promptInstruction: TEMPLATES_1LINE[i],
                namePosition: TEMPLATES_1LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_1LINE.length} x 1-line templates`);

    console.log("📝 Creating 2-line templates...");
    for (let i = 0; i < TEMPLATES_2LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `Electrician 2L-${i + 1}`,
                lines: 2,
                category: "ELECTRICIAN",
                promptInstruction: TEMPLATES_2LINE[i],
                namePosition: TEMPLATES_2LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_2LINE.length} x 2-line templates`);

    console.log("📝 Creating 3-line templates...");
    for (let i = 0; i < TEMPLATES_3LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `Electrician 3L-${i + 1}`,
                lines: 3,
                category: "ELECTRICIAN",
                promptInstruction: TEMPLATES_3LINE[i],
                namePosition: TEMPLATES_3LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_3LINE.length} x 3-line templates`);

    console.log("\n💬 Creating contexts...");
    for (let i = 0; i < CONTEXTS.length; i++) {
        await prisma.reviewContext.create({
            data: {
                userId: user.id,
                type: "scenario",
                title: `Electrician Context ${i + 1}`,
                content: CONTEXTS[i],
                category: "ELECTRICIAN",
                isActive: true,
            }
        });
        if ((i + 1) % 50 === 0) console.log(`   ...${i + 1} contexts`);
    }
    console.log(`   ✓ ${CONTEXTS.length} contexts`);

    const total = TEMPLATES_1LINE.length + TEMPLATES_2LINE.length + TEMPLATES_3LINE.length;
    console.log(`\n✅ Complete! ${total} templates + ${CONTEXTS.length} contexts for ELECTRICIAN`);
}

seed()
    .catch((e) => { console.error("❌ Error:", e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
