import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const USER_EMAIL = "demo@clientflow.local";

// Templates: 30 x 1-line, 40 x 2-line, 30 x 3-line = 100 total
// ~10% have {business_name}
const TEMPLATES_1LINE = [
    "Intervention rapide et efficace, plombier très professionnel !",
    "Excellent travail, fuite réparée en moins d'une heure.",
    "Plombier compétent et ponctuel, je recommande vivement.",
    "Dépannage urgent parfaitement géré, merci beaucoup !",
    "Travail propre et soigné, tarifs raisonnables.",
    "Installation impeccable de ma nouvelle salle de bain.",
    "Je recommande {business_name} les yeux fermés !",
    "Intervention rapide malgré le week-end, super service.",
    "Plombier sérieux et travail de qualité, satisfait.",
    "Débouchage efficace et prix correct, merci !",
    "Installation chauffe-eau parfaite, très content.",
    "Réparation WC rapide et propre, excellent.",
    "Devis clair et respecté, travail impeccable.",
    "Plombier à l'écoute et très compétent.",
    "Fuite d'eau résolue rapidement, professionnel.",
    "Excellent rapport qualité-prix pour les travaux.",
    "Intervention en urgence très appréciée, merci.",
    "Travaux de plomberie parfaitement réalisés.",
    "Artisan qualifié et respectueux, je recommande.",
    "Dépannage rapide et efficace, super service !",
    "Installation robinetterie impeccable, très satisfait.",
    "Plombier disponible et réactif, excellent travail.",
    "Rénovation salle de bain magnifique, merci !",
    "Chantier propre et travail soigné, bravo.",
    "Service client au top, travail de qualité.",
    "Pose de cumulus rapide et propre, parfait.",
    "Détection fuite précise et réparation efficace.",
    "Plombier honnête et travail sérieux, recommandé.",
    "Installation douche italienne parfaite, ravi !",
    "Dégorgement canalisations efficace et rapide.",
];

const TEMPLATES_2LINE = [
    "Intervention très rapide pour une fuite urgente sous l'évier. Le plombier a diagnostiqué le problème immédiatement et l'a réparé efficacement.",
    "Installation complète de ma nouvelle salle de bain réalisée avec soin. Travail de qualité et respect des délais, je suis très satisfait.",
    "J'ai fait appel à {business_name} pour un dépannage urgent le dimanche. Intervention rapide et professionnelle, je recommande vivement.",
    "Remplacement du chauffe-eau effectué rapidement et proprement. Le plombier a tout expliqué clairement et le prix était conforme au devis.",
    "Débouchage de mes canalisations réalisé efficacement avec le matériel adapté. Le problème est résolu et le plombier a été très professionnel.",
    "Réparation d'une fuite importante dans la salle de bain. Intervention rapide qui a évité des dégâts plus importants, merci beaucoup.",
    "Installation d'un adoucisseur d'eau parfaitement réalisée. Le plombier a pris le temps de m'expliquer le fonctionnement et l'entretien.",
    "Pose d'une nouvelle robinetterie dans toute la maison. Travail soigné et finitions impeccables, très content du résultat.",
    "Recherche de fuite avec caméra très efficace. Le problème caché a été localisé rapidement et réparé le jour même.",
    "Rénovation complète de la plomberie d'un appartement ancien. Travail de qualité et mise aux normes effectuée correctement.",
    "Installation d'un WC suspendu réalisée avec expertise. Le résultat est moderne et fonctionnel, exactement ce que je voulais.",
    "Dépannage chaudière effectué rapidement par un technicien compétent. Chauffage remis en service le soir même, parfait en hiver.",
    "Pose d'une douche à l'italienne magnifique. Le travail d'étanchéité est impeccable et le rendu est superbe.",
    "Remplacement de toute la tuyauterie en cuivre réalisé proprement. Travaux importants menés avec professionnalisme et dans les temps.",
    "Je recommande {business_name} pour leur sérieux et leur compétence. Installation de qualité et service client irréprochable.",
    "Intervention pour dégât des eaux gérée en urgence. Le plombier a limité les dégâts et effectué les réparations nécessaires.",
    "Installation d'un système de récupération d'eau de pluie. Projet écologique réalisé avec expertise et conseils pertinents.",
    "Réparation de la chasse d'eau et remplacement du mécanisme. Travail rapide et prix très correct pour la prestation.",
    "Mise en conformité de mon installation gaz effectuée sérieusement. Certificat délivré et tranquillité d'esprit assurée.",
    "Pose d'un mitigeur thermostatique parfaitement réalisée. Confort amélioré dans la douche et économies d'eau à la clé.",
    "Création d'un point d'eau supplémentaire pour ma buanderie. Travaux réalisés proprement sans casse ni dégât.",
    "Raccordement lave-vaisselle et lave-linge effectué rapidement. Plombier efficace et travail conforme aux normes.",
    "Remplacement des joints et réparation des fuites multiples. Intervention complète qui a résolu tous les problèmes.",
    "Installation complète cuisine neuve avec plomberie froide et chaude. Travail de professionnel, aucune fuite depuis.",
    "Détartrage complet de ma tuyauterie réalisé efficacement. L'eau coule maintenant normalement partout dans la maison.",
    "Vérification annuelle de mon installation par un pro sérieux. Conseils utiles et petites réparations préventives effectuées.",
    "Pose d'un ballon thermodynamique recommandée et installée parfaitement. Économies sur ma facture d'électricité déjà visibles.",
    "Réparation siphon et évacuation sous baignoire compliquée. Le plombier a trouvé une solution ingénieuse et efficace.",
    "Installation d'un surpresseur pour améliorer la pression. Travail technique bien maîtrisé et résultat conforme aux attentes.",
    "Modification du réseau d'eau pour extension maison. Raccordement parfait au réseau existant sans interruption longue.",
    "Mise en place d'un clapet anti-retour suite aux refoulements. Problème résolu définitivement par un pro compétent.",
    "Remplacement de la colonne de douche cassée très rapidement. Le nouveau modèle fonctionne parfaitement, merci.",
    "Intervention pour odeurs de canalisation résolue efficacement. Diagnostic précis et solution durable apportée par le plombier.",
    "Installation d'un WC japonais avec toutes les fonctionnalités. Travail technique bien maîtrisé et raccordements impeccables.",
    "Réparation groupe de sécurité chauffe-eau qui coulait. Intervention rapide qui a évité le gaspillage d'eau.",
    "Je fais appel à {business_name} depuis des années. Toujours satisfait de leur réactivité et de leur travail.",
    "Pose de raccords PER pour remplacer l'ancien plomb. Mise aux normes effectuée proprement et rapidement.",
    "Installation d'une pompe de relevage parfaitement réalisée. Solution technique adaptée à ma configuration particulière.",
    "Débouchage fosse septique et entretien réalisés proprement. Plombier équipé du matériel professionnel adapté.",
    "Dépannage fuite sous pression très bien géré. Le plombier a su couper l'eau et réparer rapidement.",
];

const TEMPLATES_3LINE = [
    "Nous avons fait appel à ce plombier pour la rénovation complète de notre salle de bain et nous sommes enchantés du résultat. Le travail est impeccable, du sol au plafond, avec une finition parfaite. L'équipe est ponctuelle, propre et très professionnelle.",
    "Suite à une fuite importante qui menaçait d'inonder mon appartement, le plombier est intervenu en urgence un dimanche soir. Il a su stopper la fuite rapidement et a effectué une réparation durable. Service client remarquable et grand professionnalisme.",
    "J'ai fait installer un nouveau système de chauffage par {business_name} et je suis extrêmement satisfait. De l'étude technique à la mise en service, tout a été géré parfaitement. Ma maison est maintenant bien chauffée et mes factures ont diminué.",
    "Rénovation complète de la plomberie dans notre maison des années 60 avec remplacement de toutes les conduites. Le chantier a été mené proprement malgré la complexité des travaux. Nous avons maintenant une installation aux normes et fiable.",
    "Installation d'une cuisine complète avec création des arrivées et évacuations d'eau nécessaires. Le plombier a travaillé en coordination parfaite avec le cuisiniste. Résultat impeccable sans la moindre fuite après plusieurs mois d'utilisation.",
    "Dégât des eaux important dans mon commerce résolu en urgence par cette équipe de plombiers compétents. Ils ont travaillé rapidement pour limiter les dommages et permettre la réouverture rapide. Je recommande vivement leurs services.",
    "Nous avons confié à ce plombier la création d'une salle de bain supplémentaire dans nos combles aménagés. De la conception à la réalisation, tout a été parfait. La pression d'eau et l'évacuation fonctionnent parfaitement malgré l'étage.",
    "Installation d'un système de géothermie eau-eau pour chauffer notre nouvelle maison. Travail technique complexe réalisé avec expertise. Le confort est optimal et nous faisons des économies d'énergie importantes depuis la mise en service.",
    "Remplacement de toute la plomberie en plomb de notre appartement ancien par du PER multicouche. Le plombier a travaillé proprement sans dégâts sur les murs. Installation conforme aux normes sanitaires actuelles maintenant.",
    "Je recommande vivement {business_name} pour leur professionnalisme et leur expertise en plomberie. Ils ont résolu un problème de canalisation que personne n'arrivait à diagnostiquer. Enfin tranquille après des mois de galères.",
    "Installation complète d'un spa avec tous les raccordements eau et évacuation nécessaires dans notre jardin. Le plombier a su adapter les solutions techniques aux contraintes extérieures. Nous profitons maintenant de notre spa sans problème.",
    "Travaux de mise en conformité gaz réalisés sérieusement avant la vente de notre maison. Le plombier a tout vérifié et mis aux normes. Nous avons obtenu le certificat de conformité sans difficulté grâce à leur travail.",
    "Création d'un hammam privatif avec circuit vapeur et évacuations adaptées réalisée parfaitement. Projet ambitieux mené avec expertise technique et créativité. Notre salle de bain est maintenant un véritable espace de bien-être.",
    "Suite à une inspection caméra révélant des canalisations en très mauvais état, le plombier a réalisé un chemisage complet. Technique moderne et efficace qui a évité des travaux destructifs. Canalisations rénovées sans casse.",
    "Installation d'un récupérateur de chaleur sur les eaux grises pour préchauffer l'eau sanitaire. Solution écologique et économique parfaitement mise en place. Je recommande ce plombier pour les projets innovants.",
    "Rénovation de la plomberie de notre restaurant effectuée pendant la fermeture annuelle. Travaux importants réalisés dans les temps pour permettre la réouverture. Équipe réactive et compétente, très satisfait.",
    "Pose d'un système de traitement complet de l'eau de toute la maison avec adoucisseur et osmoseur. Installation complexe parfaitement réalisée et expliquée. La qualité de notre eau s'est nettement améliorée.",
    "Intervention en urgence pour une canalisation principale bouchée menaçant tout l'immeuble. Le plombier a travaillé de nuit pour résoudre le problème avant le matin. Professionnalisme exemplaire dans une situation critique.",
    "Installation d'un chauffe-eau solaire avec appoint électrique pour notre maison en Provence. Système parfaitement dimensionné et installé proprement. Nous avons de l'eau chaude gratuite presque toute l'année.",
    "Réfection complète des sanitaires d'un local professionnel avec création de douches vestiaires. Travaux aux normes PMR réalisés correctement. Inspection validée sans réserve grâce au sérieux du plombier.",
    "Nous avons fait appel à {business_name} pour installer un système de récupération d'eau de pluie pour nos WC et le jardin. Installation fonctionnelle et économies d'eau substantielles réalisées depuis la mise en service.",
    "Dépannage d'une chaudière ancienne que tout le monde voulait remplacer mais que le plombier a su réparer. Diagnostic précis et réparation économique. La chaudière fonctionne de nouveau parfaitement depuis.",
    "Installation d'un circuit de chauffage au sol hydraulique dans notre extension en plein hiver. Le plombier a su gérer les contraintes techniques et climatiques. Confort optimal maintenant dans cette nouvelle pièce.",
    "Raccordement au réseau d'assainissement collectif réalisé proprement lors des travaux de voirie. Procédures administratives accompagnées et travaux conformes aux exigences de la commune. Service complet apprécié.",
    "Création d'un laboratoire de cuisine professionnelle avec toutes les évacuations et arrivées d'eau nécessaires. Travail conforme aux normes sanitaires strictes de la restauration. Inspection DDPP validée du premier coup.",
    "Installation d'une pompe à chaleur air-eau pour remplacer notre vieille chaudière fioul polluante. Transition énergétique réussie grâce à ce plombier chauffagiste compétent. Confort maintenu et factures réduites.",
    "Réparation d'une fuite enterrée dans le jardin détectée par un pic de consommation inexpliqué. Recherche de fuite efficace et réparation discrète. Le gazon est intact et nous ne consommons plus d'eau inutilement.",
    "Pose d'une VMC double flux avec récupération de chaleur intégrée à notre système de chauffage hydraulique. Installation technique parfaitement réalisée. Air sain et économies d'énergie combinées maintenant.",
    "Installation d'un surpresseur collectif pour notre copropriété souffrant de basse pression aux étages élevés. Solution technique adaptée et installation validée par le syndic. Tous les résidents sont maintenant satisfaits.",
    "Création d'une salle d'eau complète dans un studio en rez-de-jardin avec pompe de relevage. Contraintes techniques parfaitement maîtrisées par le plombier. L'évacuation fonctionne sans aucun problème depuis.",
];

// 200 contexts
const CONTEXTS = [
    "Réparation fuite sous évier",
    "Installation chauffe-eau thermodynamique",
    "Débouchage canalisation cuisine",
    "Remplacement robinetterie salle de bain",
    "Dépannage urgent dimanche",
    "Pose douche à l'italienne",
    "Installation WC suspendu",
    "Recherche fuite non visible",
    "Rénovation plomberie appartement",
    "Remplacement cumulus électrique",
    "Mise aux normes installation gaz",
    "Installation adoucisseur d'eau",
    "Débouchage WC bouché",
    "Réparation chasse d'eau",
    "Pose mitigeur thermostatique",
    "Création point d'eau buanderie",
    "Raccordement lave-vaisselle",
    "Détartrage tuyauterie",
    "Installation surpresseur",
    "Réparation fuite ballon d'eau chaude",
    "Dégorgement fosse septique",
    "Remplacement siphon baignoire",
    "Installation pompe de relevage",
    "Réparation groupe de sécurité",
    "Pose colonne de douche",
    "Débouchage évacuation douche",
    "Modification réseau eau",
    "Installation récupérateur eau pluie",
    "Réparation canalisation extérieure",
    "Remplacement tuyau alimentation",
    "Pose clapet anti-retour",
    "Installation système filtration",
    "Dépannage chaudière gaz",
    "Réparation radiateur qui fuit",
    "Purge circuit chauffage",
    "Désembouage radiateurs",
    "Installation vanne thermostatique",
    "Réparation fuite collecteur",
    "Pose de raccords PER",
    "Soudure tuyau cuivre",
    "Installation bac à douche",
    "Remplacement flexible douche",
    "Réparation joint robinet",
    "Débouchage siphon lavabo",
    "Installation lave-mains WC",
    "Pose douchette économique",
    "Réparation fuite radiateur",
    "Installation vase d'expansion",
    "Remplacement circulateur chauffage",
    "Mise en service chaudière",
    "Fuite sous mon évier depuis ce matin",
    "Plus d'eau chaude depuis hier soir",
    "WC bouché qui déborde",
    "Mauvaise odeur canalisations",
    "Pression eau trop faible",
    "Robinet qui goutte la nuit",
    "Chauffe-eau qui fait du bruit",
    "Fuite dans le mur invisible",
    "Canalisation gelée en hiver",
    "Évacuation lente de la douche",
    "Eau marron au robinet",
    "Ballon qui coule en permanence",
    "Radiateur qui ne chauffe plus",
    "Bruit dans les tuyaux",
    "Compteur qui tourne tout seul",
    "Traces humidité plafond",
    "Fuite raccord lave-linge",
    "Mitigeur bloqué calcaire",
    "Siphon fissuré baignoire",
    "Chasse d'eau qui coule",
    "Joint silicone moisi",
    "Tuyau PER percé",
    "Vanne d'arrêt bloquée",
    "Flexible douche percé",
    "Évacuation bouchée graisses",
    "Chaudière en panne hiver",
    "Pas de chauffage matin",
    "Radiateur qui siffle",
    "Pression chaudière trop basse",
    "Fuite circuit chauffage",
    "Devis rénovation salle de bain",
    "Devis installation douche italienne",
    "Devis remplacement chauffe-eau",
    "Devis plomberie maison neuve",
    "Devis mise aux normes",
    "Devis création salle d'eau",
    "Devis adoucisseur d'eau",
    "Devis pompe à chaleur",
    "Devis récupération eau pluie",
    "Devis chauffage au sol",
    "Plombier pour SCI immeuble",
    "Plombier copropriété urgence",
    "Contrat entretien chaudière",
    "Intervention assurance dégât eaux",
    "Plombier agréé gaz",
    "Plombier RGE aides",
    "Recherche artisan sérieux",
    "Recommandation plombier quartier",
    "Avis plombier pas cher",
    "Plombier disponible week-end",
    "Urgence plomberie nuit",
    "Dépannage plomberie 24h/24",
    "Plombier proche chez moi",
    "Artisan plombier recommandé",
    "Plombier devis gratuit",
    "Plombier garantie décennale",
    "Installation cuisine équipée",
    "Raccordement îlot central cuisine",
    "Évacuation évier professionnel",
    "Création local technique",
    "Installation fontaine à eau",
    "Pose évier double bac",
    "Raccordement broyeur évier",
    "Installation eau osmosée cuisine",
    "Arrivée eau réfrigérateur",
    "Robinet douchette cuisine",
    "Rénovation plomberie immeuble 1900",
    "Remplacement colonne montante",
    "Création colonnes EU EP",
    "Raccordement tout à l'égout",
    "Séparation eaux usées pluviales",
    "Mise en conformité assainissement",
    "Curage canalisation enterrée",
    "Inspection caméra canalisation",
    "Chemisage canalisation sans tranchée",
    "Réparation canalisation fissurée",
    "Installation spa jacuzzi",
    "Raccordement piscine filtration",
    "Circuit chauffage piscine",
    "Installation douche extérieure",
    "Arrosage automatique jardin",
    "Fontaine de jardin circuit",
    "Récupérateur eau pluie enterré",
    "Pompage eau de puits",
    "Forage eau particulier",
    "Traitement eau de source",
    "Installation hammam vapeur",
    "Circuit balnéo baignoire",
    "Colonne hydromassage",
    "Sauna raccordement eau",
    "Douche sensorielle installation",
    "WC japonais lavant",
    "Urinoir sans eau",
    "Lavabo PMR adapté",
    "Barre de maintien douche",
    "Siège de douche rabattable",
    "Local professionnel plomberie",
    "Restaurant cuisine aux normes",
    "Laboratoire traiteur équipement",
    "Boulangerie arrivée eau",
    "Salon coiffure bacs",
    "Cabinet dentaire stérilisation",
    "Clinique vétérinaire sanitaires",
    "Garage auto fosse vidange",
    "Pressing buanderie industrielle",
    "Crèche sanitaires enfants",
    "Chaudière gaz condensation",
    "Pompe à chaleur air-eau",
    "Chaudière bois granulés",
    "Chauffe-eau solaire CESI",
    "Plancher chauffant hydraulique",
    "Radiateurs basse température",
    "Circuit VMC double flux",
    "Récupérateur chaleur eaux grises",
    "Ballon tampon installation",
    "Vanne trois voies motorisée",
    "Contrat entretien annuel",
    "Révision chaudière obligatoire",
    "Ramonage conduit fumée",
    "Désembouage circuit chauffage",
    "Analyse qualité eau",
    "Contrôle conformité gaz",
    "Certificat conformité GRDF",
    "Diagnostic assainissement",
    "Expertise fuite assurance",
    "Rapport intervention détaillé",
    "Réparation fuite dimanche",
    "Débouchage urgent férié",
    "Chauffage panne nuit",
    "Plus d'eau chaude matin",
    "WC unique bouché urgence",
    "Inondation appartement",
    "Fuite importante visible",
    "Coupure eau immeuble",
    "Odeur gaz urgence",
    "Dégât des eaux plafond",
    "Économies eau installation",
    "Réduction facture chauffage",
    "Aides rénovation énergétique",
    "MaPrimeRénov plomberie",
    "CEE prime énergie",
    "Éco-PTZ travaux",
    "TVA réduite rénovation",
    "Crédit impôt transition",
    "Subvention collectivité locale",
    "Audit énergétique maison",
];

async function seed() {
    console.log("🔧 Seeding Plumber data...\n");

    const user = await prisma.user.findFirst({ where: { email: USER_EMAIL } });
    if (!user) {
        console.error(`❌ User ${USER_EMAIL} not found!`);
        return;
    }
    console.log(`✓ Found user: ${user.email}\n`);

    // Insert 1-line templates
    console.log("📝 Creating 1-line templates...");
    for (let i = 0; i < TEMPLATES_1LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `Plumber 1L-${i + 1}`,
                lines: 1,
                category: "PLUMBER",
                promptInstruction: TEMPLATES_1LINE[i],
                namePosition: TEMPLATES_1LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_1LINE.length} x 1-line templates`);

    // Insert 2-line templates
    console.log("📝 Creating 2-line templates...");
    for (let i = 0; i < TEMPLATES_2LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `Plumber 2L-${i + 1}`,
                lines: 2,
                category: "PLUMBER",
                promptInstruction: TEMPLATES_2LINE[i],
                namePosition: TEMPLATES_2LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_2LINE.length} x 2-line templates`);

    // Insert 3-line templates
    console.log("📝 Creating 3-line templates...");
    for (let i = 0; i < TEMPLATES_3LINE.length; i++) {
        await prisma.reviewTemplate.create({
            data: {
                userId: user.id,
                name: `Plumber 3L-${i + 1}`,
                lines: 3,
                category: "PLUMBER",
                promptInstruction: TEMPLATES_3LINE[i],
                namePosition: TEMPLATES_3LINE[i].includes("{business_name}") ? "middle" : "none",
                isActive: true,
            }
        });
    }
    console.log(`   ✓ ${TEMPLATES_3LINE.length} x 3-line templates`);

    // Insert contexts
    console.log("\n💬 Creating contexts...");
    for (let i = 0; i < CONTEXTS.length; i++) {
        await prisma.reviewContext.create({
            data: {
                userId: user.id,
                type: "scenario",
                title: `Plumber Context ${i + 1}`,
                content: CONTEXTS[i],
                category: "PLUMBER",
                isActive: true,
            }
        });
        if ((i + 1) % 50 === 0) console.log(`   ...${i + 1} contexts`);
    }
    console.log(`   ✓ ${CONTEXTS.length} contexts`);

    const total = TEMPLATES_1LINE.length + TEMPLATES_2LINE.length + TEMPLATES_3LINE.length;
    console.log(`\n✅ Complete! ${total} templates + ${CONTEXTS.length} contexts for PLUMBER`);
}

seed()
    .catch((e) => { console.error("❌ Error:", e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
